name: Custom GitHub Action

on:
  push:
    branches:
      - main  # Change if needed
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 23f1002587@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Complete Action
        run: echo "GitHub Action triggered successfully!"
